#!/bin/bash

function join_by { local IFS="$1"; shift; echo "$*"; }

if [ "$1" = new_game ]; then
  if [ "$2" = players.txt ]; then
    readarray -t players < players.txt
  else
    players=( "$@" )
  fi
  for (( i=0; i<${#players[@]}; i++ )); do
      if ! test -z "$(echo -n "${players[$i]}" | tr -d 'a-zA-Z0-9')"; then
        echo "Bad address"
        exit 1
      fi
  done
  args="$(join_by "&" "${players[@]}")"
  curl -s -S "https://coinballer.net/new_game?$args"
fi

if [ "$1" = status ]; then
  game_id="$2"
  if ! test -z "$(echo -n "$game_id" | tr -d 'a-zA-Z0-9')"; then
    echo "Bad game status"
    exit 1
  fi
  curl -s -S "https://coinballer.net/status?$game_id"
fi

